import type { Metadata } from "next";
import { Raleway, Montserrat, Geist, Geist_Mono, Monoton } from "next/font/google";
import "./globals.css";
import { Fraunces } from "next/font/google";
import ScrollProvider from "./providers/lenis-provider";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";


const monoton = Monoton({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-monoton',
});

// Load the fonts
const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fraunces",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fraunces.variable} ${raleway.variable} ${montserrat.variable} ${monoton.variable} antialiased bg-[#081C29] text-white`}
        suppressHydrationWarning={true}
      >
        <NavBar />
        <ScrollProvider>
          {children}
        </ScrollProvider>
        <Footer />

      </body>
    </html>
  );
}
